name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: maximousblk/setup-deno@v1

      - name: Lint
        run: deno lint

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: maximousblk/setup-deno@v1

      - name: Lint
        run: deno fmt --check
