# TODO(@maximousblk): add docker build workflows

name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2

      - name: Generate Release Notes
        # TODO(@maximousblk): switch to nest when new registry is released
        run: deno run -A https://deno.land/x/ghlog@0.3.0/ghlog.ts ${{ github.repository }} -v '${{ github.event.inputs.tag }}'
